### PR TITLE
Add comment to do

### PR DESCRIPTION
**Pull request by DongTrieu1998**

### CODE REVIEW

**Comment by ghost** [comment]
Hi @DongTrieu1998, please refactor the main Application

**Comment by DongTrieu1998** [comment]
I will check it, thank you.

**Comment by ghost** [comment]
@DongTrieu1998 any update ?

**Comment by DongTrieu1998** [comment]
I have just push latest code and create a pull request. Please review it. Thank you.
FYI: @thanhdat369

**Pull request merged**
