### PR TITLE
Add menu bar

### PR DESCRIPTION
**Pull request by DongTrieu1998**
Add menu bar with an app's icon and tools's icon

### CODE REVIEW

**Comment by DongTrieu1998** [comment]
@thanhdat369 please check it, thanck you.

**Comment by DongTrieu1998** [comment]
I added icon for Menu Bar tools. please check it. @thanhdat369

**Comment by ghost** [comment]
It's oke now. Please merge it into the main branch. You should refactor it later

**Review by ghost — APPROVED** [review]

**Comment by DongTrieu1998** [comment]
It’s done, thank @thanhdat369

**Pull request merged**
